apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${SERVICE}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /hello(/|$)(.*)
            backend:
              serviceName: hello-service
              servicePort: 8080
            path: /hello
