apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - backend:
            service:
              name: hello-service
              port:
                number: 8080
          path: /hello(/|$)(.*)
          pathType: ImplementationSpecific
